### ISSUE TITLE
feature: init chat with contexts

### ISSUE THREAD

**Issue by phodal** [prompt-engineering/click-prompt#100]
Chinese: 为了帮助 ChatGPT 更好地理解用户意图和上下文，在与 ChatGPT 进行初次对话时，添加一个包含一系列信息的上下文环境，以用于特定场景的使用，如聊天机器人。

**Is your feature request related to a problem? Please describe.** 

Currently, when using ChatGPT for certain applications like chatbots, the model requires some initial information about the context or scenario it will be used in. This can be a time-consuming and cumbersome process for users.

**Describe the solution you'd like**

 I would like to have the ability to provide some initial information to ChatGPT when using it for the first time in a specific context or scenario. This information can be in the form of prompts or other relevant data that will help the model generate more relevant and accurate responses.

**Describe alternatives you've considered** 

One alternative would be to manually input the initial information each time the model is used in a new scenario. However, this is time-consuming and could result in errors or inconsistencies.

**Additional context** 

This feature would be particularly useful for applications like chatbots, where the initial context is critical to providing accurate and relevant responses. Having the ability to provide this information to ChatGPT when using it for the first time in a specific scenario would greatly improve the user experience and the overall performance of the model.

**Comment by CGQAQ** [comment]
You just need to create an empty conversation, and then you can send multiple chats at once to provide context
