### ISSUE TITLE
feature: save ClickFlow result for use cache value

### ISSUE THREAD

**Issue by phodal** [prompt-engineering/click-prompt#117]
**Is your feature request related to a problem? Please describe.** 

No, this feature request is not related to a problem.

**Describe the solution you'd like**

 We would like to add a new feature to ClickPrompt where users can save a custom ChatGPT result based on their specific needs. This feature would allow users to input their own text prompts and receive a customized response from ChatGPT. The saved results would be accessible to the user at any time.

**Describe alternatives you've considered** 

We have considered allowing users to save their own prompts and responses, but we believe that allowing users to save a customized ChatGPT result would be more useful and efficient.

**Additional context** 

We believe that this feature would be beneficial for users who frequently use ChatGPT for specific tasks or projects. It would save them time and effort by allowing them to quickly access their customized results without having to input the same prompts repeatedly.

**Comment by tiwentichat** [comment]
我看到chatgpt的回复可以复制到剪贴板，不知道整个对话记录可以一次性复制嘛？ 毕竟是整个flow

**Comment by phodal** [comment]
欢迎来个 pr

**Comment by tiwentichat** [comment]
> 欢迎来个 pr

我也想，技术太菜。。。

**Comment by phodal** [comment]
done by https://github.com/prompt-engineering/chat-flow
