### ISSUE TITLE
不知道算不算bug..clickflow页面的写作示例，前端体验在输入框修改文本的时候会中断

### ISSUE THREAD

**Issue by tiwentichat** [prompt-engineering/click-prompt#131]
**Describe the bug**
在clickprompt.org的click flow页面下面试用，点击其中的 写作 示例展开，然后修改prompt的内容细节，输入一个字母后就会中断，或者删除一个字，也会中断，需要重新选中输入框...

mac系统，chrome浏览器和safari浏览器都这样，其他示例不会出现，只会出现在写作那个示例

**Comment by phodal** [comment]
应该是 bug，欢迎来 pr
