### ISSUE TITLE
运行npm run dev后报错failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:

### ISSUE THREAD

**Issue by codeseedling** [prompt-engineering/click-prompt#135]
下图是运行npm run dev后报的错，请问我应该怎么做呢，当我使用API-key登录ChatGPT时也没有反应
![image](https://user-images.githubusercontent.com/103105509/235071246-d16b09b7-cbc2-4bbe-89d0-730f5b4385d7.png)
![image](https://user-images.githubusercontent.com/103105509/235072017-ee1fad9e-0178-4d02-9d21-32444c46563c.png)

**Comment by phodal** [comment]
看上去不是依赖没安装上吗

**Comment by codeseedling** [comment]
> 看上去不是依赖没安装上吗

是的，确实依赖没装上，谢谢
