### ISSUE TITLE
可以直接调用 ChatGPT 接口，直接执行 Prompt

### ISSUE THREAD

**Issue by phodal** [prompt-engineering/click-prompt#15]

**Comment by phodal** [comment]
点击对应的 ClickPrompt Button，类似于这里：

<img width="208" alt="图片" src="https://user-images.githubusercontent.com/472311/223900029-17dbaa9e-a932-4a27-a64b-5357b5bc68e0.png">

**Comment by phodal** [comment]
@CGQAQ already finished ?

**Comment by KAIYI-HSU** [comment]
我在本地端 npm run dev   進入3000port網頁後，無法看到這個按鈕

**Comment by KAIYI-HSU** [comment]
這是我直接從vs code 開啟網址後的畫面
![image](https://user-images.githubusercontent.com/73111412/223900519-722a3712-9d55-4c02-a491-95b962f861f7.png)

**Comment by KAIYI-HSU** [comment]
![image](https://user-images.githubusercontent.com/73111412/223900598-8f29e11b-53d4-431b-b1ac-438f1de93992.png)
這是左上角圖標(首頁)

**Comment by phodal** [comment]
有没有可能代码比较老？拉一个最新的试试？最新版本，右上角已经有 中文/EN 语言切换了

**Comment by KAIYI-HSU** [comment]
感謝您，我原先是從您最新的更新頁面下載0.1.0 zip檔案，剛才重新git clone 同一版本現在成功了
p.s 原本 0.1.0的 logo 寬邊長也會出現error，但現在都沒問題了。
感謝您
