### ISSUE TITLE
bug: [Card]布局会折行

### ISSUE THREAD

**Issue by liruifengv** [prompt-engineering/click-prompt#29]
![image](https://user-images.githubusercontent.com/25167721/223012362-5a5ab8de-4583-43d0-be4e-2b0a62ac9564.png)
![image](https://user-images.githubusercontent.com/25167721/223012408-52b0e009-3a45-4ea9-90b2-ee9a7d8586dd.png)

很奇怪的问题，need help

期待：不会折断整个 Card，瀑布流？

**Comment by morehardy** [comment]
#30
