### ISSUE TITLE
awesome-chatgpt-prompts支持中英文版本搜索

### ISSUE THREAD

**Issue by sxyseo** [prompt-engineering/click-prompt#44]
提供中英文awesome-chatgpt-prompts版本搜索

**Comment by sxyseo** [comment]
@CGQAQ

**Comment by phodal** [comment]
可以参考一下中文版的：https://github.com/PlexPt/awesome-chatgpt-prompts-zh

**Comment by sxyseo** [comment]
@phodal https://github.com/prompt-engineering/click-prompt/pull/57

**Comment by sxyseo** [comment]
由于之前有冲突，重新pull https://github.com/prompt-engineering/click-prompt/pull/58

**Comment by sxyseo** [comment]
ok
