### ISSUE TITLE
[improvement] fix errors and warnings in devtool

### ISSUE THREAD

**Issue by teobler** [prompt-engineering/click-prompt#76]
![image](https://user-images.githubusercontent.com/26424691/223667024-a3c47fed-8569-491c-9ea4-c0325b82e361.png)

**Comment by genffy** [comment]
`no-console`,`no-unused-vars` should be linted

**Comment by genffy** [comment]
> `no-console`,`no-unused-vars` should be linted

https://github.com/prompt-engineering/click-prompt/pull/83

**Comment by teobler** [comment]
Thanks for help, will close this issue then
