### ISSUE TITLE
AI繪圖生成器 error

### ISSUE THREAD

**Issue by KAIYI-HSU** [prompt-engineering/click-prompt#81]
![image](https://user-images.githubusercontent.com/73111412/223920816-7f529eba-950d-486d-bc77-6231bb9ab46f.png)
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'split')

**Comment by KAIYI-HSU** [comment]
請問我稍早在舊版本可以打開，最新版本的卻無法開啟http://localhost:3000/zh-CN/stable-diffusion-generator/

**Comment by phodal** [comment]
看上去像没有空值处理

**Comment by KAIYI-HSU** [comment]
請問您clone 您最新的程式碼，這部分測試成功嗎?
我能怎麼處理比較恰當呢?

**Comment by phodal** [comment]
哈哈，你要来个 Pull Request 修复一下吗？

**Comment by KAIYI-HSU** [comment]
我沒接觸過著個語言，但如果有機會我會嘗試修復。
p.s 聊天室透過 Enter按鍵觸發發送文字似乎也沒辦法。會跳窗提醒 沒有文字。
我檢查過發現目前好像只能用onClick觸發 send。

**Comment by phodal** [comment]
那这个我来修复吧~，那个聊天室，你要不再建个新 issue ？

**Comment by phodal** [comment]
修复了，你拉取一下代码试试，线上也 ok 了：https://www.clickprompt.org/zh-CN/stable-diffusion-generator/
