### ISSUE TITLE
feature request: add stream based chatgpt api

### ISSUE THREAD

**Issue by CGQAQ** [prompt-engineering/click-prompt#86]
ref: https://github.com/openai/openai-node/issues/18

ref: https://github.com/CGQAQ/chatgpt-sse-hide-example

## Blocking

- [ ] Figuring out how to do SSE in Next.js on Vercel deploy

## code snippet
![image](https://user-images.githubusercontent.com/15936231/223976609-589ec51a-0002-40cf-b157-fc73486d23b4.png)

**Comment by genffy** [comment]
demo: https://github.com/genffy/nextjs-chatgpt-demo

**Comment by genffy** [comment]
Edge Runtime does not support [`node:crypto`](https://nextjs.org/docs/messages/node-module-in-edge-runtime)  , try to adapter it
