### ISSUE TITLE
feat: add pagination for  role play prompt

### ISSUE THREAD

**Issue by deancn** [prompt-engineering/click-prompt#91]
**Is your feature request related to a problem? Please describe.**
For now, we have lots of prompts for role play.    
I think we can split to few pages, can make the page clean and fast to load.

**Describe the solution you'd like**
pagination.  

**Describe alternatives you've considered**
Echa page show about 15 or 20 items, and support  "next", "previous".
For the url page number is better to have.

**Additional context**
Better to have in the future:  hot or suggest label.

**Comment by whatwewant** [comment]
:wip: trying

**Comment by genffy** [comment]
> trying

Sorry I didn't mark it here ToT

**Comment by phodal** [comment]
@genffy 下次记得先回一下

**Comment by whatwewant** [comment]
> > trying
> 
> Sorry I didn't mark it here ToT

[ThumbsUp] 没事没事，你做的快，效果比我的好 [Happy]
